project:
  type: website

website:
  title: "Math 32"
  site-url: https://www.dsollberger.com
  description: "Lecture Slides for Math 32"
  navbar:
    right:
      - text: Slides
        href: slides.qmd
format:
  html:
    theme: cerulean
    css: styles.css



